# Review data in app.sqlite

This notebook loads the local SQLite database and shows users, reviews, entities, and review-entity links.

In [25]:
import pandas as pd
import sqlite3
from pathlib import Path

db_path = Path('../entity-driven/data/app.sqlite')
if not db_path.exists():
    raise FileNotFoundError(f'Database not found at {db_path.resolve()}')

conn = sqlite3.connect(db_path)
conn.row_factory = sqlite3.Row

def show_old(query, params=None):
    params = params or ()
    cur = conn.execute(query, params)
    rows = cur.fetchall()
    return [dict(row) for row in rows]


def show(query, params=None):
    params = params or ()
    cur = conn.execute(query, params)
    rows = cur.fetchall()
    return pd.DataFrame(rows, columns=rows[0].keys() if rows else [])

In [26]:
cursor = conn.cursor()

cursor.execute("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
""")

tables = [row[0] for row in cursor.fetchall()]
print(tables)

['edges', 'entity', 'nodes', 'review', 'review_entity', 'sqlite_sequence', 'user']

In [29]:
show('SELECT * FROM nodes')

    id            name           type
0    1         BHC 쏘마치        default
1    2  처가집 양념통닭 K마라치킨        default
2    3            멕시카나        default
3    4               배        default
4    5          비비큐 맵소        default
5    6            노랑통닭        default
6    9              배민        default
7   10         비비큐 맵소디        default
8   11        푸라닭 깐풍치킨        default
9   12   교촌치킨 간장/레드 반반        default
10  13            자담치킨        default
11  14             땡겨요        default
12  19           고추바사삭        default
13  20            굽네치킨        default
14  21           명성왕족발        default
15  22          성남현대시장        default
16  23            귀한족발        default
17  24              성남        default
18  25           할머니족발        default
19  26         풀무원 감자전        default
20  27      풀무원 오징어부추전        default
21  28        속초 동해닭강정        default
22  29      한사랑 정형외과의원        default
23  30        이주철마취과의원        default
24  31              분당        default
25  32         미금더튼튼의원        default
26  34            정동마트        default
27  35            홈플러스        default
28  36             이마트        default
29  37              치킨  menu_category

In [11]:
# Users
show('SELECT * FROM user ORDER BY id')

   id user_id password
0   1     lbk     1234
1   2     kbl     1234

In [12]:
# Reviews (latest first)
show(
    'SELECT id, user_id, created_at, updated_at, content FROM review ORDER BY COALESCE(updated_at, created_at) DESC'
)

,id,user_id,created_at,updated_at,content
0,22,1,2025-12-29T09:21:47.577Z,2025-12-29T09:21:47.577Z,앱에서 맥주 재고 확인하고 직접 마트 가니까 아무리 찾아도 못찾겠다. 집에 와서 보...
1,21,2,2025-12-29T09:20:45.197Z,2025-12-29T09:20:45.197Z,4개 한셋트 치약 1+1 세일한다기에 사고 보니 3개 한셋트 치약이었다. 영수증엔 ...
2,20,2,2025-12-29T09:20:17.511Z,2025-12-29T09:20:17.511Z,홈플러스 앱으로 와인 주문: 10만원 이상 사면 20%할인한다기에 가격 맞춰 3병 ...
3,19,1,2025-12-29T09:19:50.904Z,2025-12-29T09:19:50.904Z,정자동 정동마트에서 종종 바나나 세일을 하는데 대부분 거무죽죽하니 신선도 관리를 어...
4,18,1,2025-12-29T09:18:58.976Z,2025-12-29T09:18:58.976Z,예전에 땡겨요에서 세일하길래 무슨 요리 배달 주문했더니 배달에 한시간 이상 걸린다고...
5,17,2,2025-12-29T09:18:02.078Z,2025-12-29T09:18:02.078Z,며칠이 니자도 발뒤꿈치가 아파 미금역 근처 정형외과를 찾아갔다. 아킬레스건염 같은 ...
6,16,2,2025-12-29T09:17:13.163Z,2025-12-29T09:17:13.163Z,발뒤꿈치가 아파 정형외과를 찾는데 저번에 비싼 주사 맞은데를 피해서 다른 병원을 갔...
7,15,2,2025-12-29T09:16:18.396Z,2025-12-29T09:16:18.396Z,엄지 발가락이 아파서 동네 정형외과 갔다가 얼떨결에 비급여 10만원짜리 주사 맞고 ...
8,14,1,2025-12-29T09:15:40.337Z,2025-12-29T09:15:40.337Z,속초에서 시장 구경하고 돌아가는 길 닭강정 사는걸 깜빡했다. 많은 사람들이 만석닭강...
9,13,1,2025-12-29T09:15:16.784Z,2025-12-29T09:15:16.784Z,마트에서 풀무원 감자전/오징어부추전 구입. 에어프라이로 조리했는데 기름 범벅. 후라...
10,12,1,2025-12-29T09:14:35.950Z,2025-12-29T09:14:35.950Z,민생지원금으로 성남 할머니 족발에서 족발 포장. 잡내 없고 맛나다. 다음에 명성왕족...
11,11,1,2025-12-29T09:14:05.512Z,2025-12-29T09:14:05.512Z,귀한족발에서 족발 배달시켰는데 막국수 반찬까지 있는건 좋지만 정작 족발맛이 아쉽다
12,10,1,2025-12-29T09:13:40.947Z,2025-12-29T09:13:40.947Z,성남 현대시장 명성왕족발에서 족발 대자 포장. 싸고 맛 좋고 특히 온누리상품권을 쓸...
13,9,1,2025-12-29T09:12:47.282Z,2025-12-29T09:12:47.282Z,굽네치킨에서 유일하게 좋아하는 고추바사삭. 근데 살이 너무 없는것 같다
14,8,2,2025-12-29T08:36:49.478Z,2025-12-29T09:06:16.047Z,땡겨요에서 할인을 크게 해서 한동안 집앞 자담치킨 참 많이도 포장해 먹었다. 왓더핫...
15,7,2,2025-12-29T08:35:56.715Z,None,교촌치킨에서 간장 레드 반반 주문. 간장만 먹으면 심심하고 레드만 먹으면 자극적이면...
16,6,2,2025-12-29T08:35:01.386Z,None,푸라닭에서 유명 쉐프와 협업했다는 깐풍치킨 주문. 소스가 볶은 느낌이 아니라 흥건하...
17,5,2,2025-12-29T07:59:37.482Z,None,노랑통닭은 순살도 가격이 더 비싸지 않아 좋다. 튀김 부스러기는 과자같이 바삭하니 ...
18,4,2,2025-12-29T07:58:38.948Z,None,비비큐에서 맵소디 배달 주문. 양념 맛은 기억나지 않지만 소스 안쪽에서도 바삭한 식...
19,3,1,2025-12-29T07:54:49.553Z,None,배달앱에서 멕시카나 치킨 할인한다기에 주문하려했더니 미금점 영업을 하지 않는다. 이...
20,2,1,2025-12-29T07:53:41.320Z,None,처가집 양념통닭에서 마라치킨 주문. 그냥 달달한 양념 치킨에 마라향 살짝 추가한 정...
21,1,1,2025-12-26T09:39:18.074Z,None,BHC서현시범단지점. 근처 지점중 배달 최수 주문가가 가장 저렴해 치킨 주문. 쏘마...

In [24]:
# Entities
df = show('SELECT * FROM entity ORDER BY id')
df['name'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
Name: name, dtype: bool

In [28]:
df = df.loc[~df['id'].isin([4, 5])]
df = df.set_index('id')
df

              name  type level parent_id
id
1          BHC 쏘마치  None  None      None
2   처가집 양념통닭 K마라치킨  None  None      None
3             멕시카나  None  None      None
6             노랑통닭  None  None      None
9               배민  None  None      None
10         비비큐 맵소디  None  None      None
11        푸라닭 깐풍치킨  None  None      None
12   교촌치킨 간장/레드 반반  None  None      None
13            자담치킨  None  None      None
14             땡겨요  None  None      None
19           고추바사삭  None  None      None
20            굽네치킨  None  None      None
21           명성왕족발  None  None      None
22          성남현대시장  None  None      None
23            귀한족발  None  None      None
24              성남  None  None      None
25           할머니족발  None  None      None
26         풀무원 감자전  None  None      None
27      풀무원 오징어부추전  None  None      None
28        속초 동해닭강정  None  None      None
29      한사랑 정형외과의원  None  None      None
30        이주철마취과의원  None  None      None
31              분당  None  None      None
32         미금더튼튼의원  None  None      None
34            정동마트  None  None      None
35            홈플러스  None  None      None
36             이마트  None  None      None

In [36]:
#ids = [1,2,10,11,12,19,26,27]
#df.loc[ids, 'type'] = 'product'

#ids = [3,6,13,20,21,23,25,28,29,30,32,34,35,36]
ids = [9,14,22]
df.loc[ids, 'type'] = 'vendor'
#df.loc[df['type'].isna()]

In [38]:
ids = [24,31]
df.loc[ids, 'type'] = 'location'
df.loc[df['type'].isna()]

Empty DataFrame
Columns: [name, type, level, parent_id]
Index: []

In [43]:
df

              name      type level parent_id
id
1          BHC 쏘마치   product  None      None
2   처가집 양념통닭 K마라치킨   product  None      None
3             멕시카나    vendor  None      None
6             노랑통닭    vendor  None      None
9               배민    vendor  None      None
10         비비큐 맵소디   product  None      None
11        푸라닭 깐풍치킨   product  None      None
12   교촌치킨 간장/레드 반반   product  None      None
13            자담치킨    vendor  None      None
14             땡겨요    vendor  None      None
19           고추바사삭   product  None      None
20            굽네치킨    vendor  None      None
21           명성왕족발    vendor  None      None
22          성남현대시장    vendor  None      None
23            귀한족발    vendor  None      None
24              성남  location  None      None
25           할머니족발    vendor  None      None
26         풀무원 감자전   product  None      None
27      풀무원 오징어부추전   product  None      None
28        속초 동해닭강정    vendor  None      None
29      한사랑 정형외과의원    vendor  None      None
30        이주철마취과의원    vendor  None      None
31              분당  location  None      None
32         미금더튼튼의원    vendor  None      None
34            정동마트    vendor  None      None
35            홈플러스    vendor  None      None
36             이마트    vendor  None      None

In [46]:
idx = [37, 38, 39]

df = df.reindex(df.index.union(idx))

df.loc[idx, ['name', 'type']] = [
    ['치킨', 'product'],
    ['병원', 'service'],
    ['마트', 'service'],
]

In [48]:
df.to_csv('entities.csv')

In [14]:
# Review-entity links
show(
    'SELECT review_id, entity_id FROM review_entity ORDER BY review_id, entity_id'
)

    review_id  entity_id
0           1          1
1           2          2
2           3          3
3           3          9
4           4         10
5           5          6
6           6         11
7           7         12
8           8         13
9           8         14
10          9         19
11          9         20
12         10         21
13         10         22
14         11         23
15         12         24
16         12         25
17         13         26
18         13         27
19         14         28
20         15         29
21         16         30
22         16         31
23         17         32
24         18         14
25         19         34
26         20         35
27         21         36
28         22         36

In [19]:
# Joined view: reviews with entity names
show(
    '''
    SELECT r.id, r.user_id, r.created_at, r.updated_at, r.content,
           GROUP_CONCAT(e.name, ', ') AS entities
    FROM review r
    LEFT JOIN review_entity re ON r.id = re.review_id
    LEFT JOIN entity e ON e.id = re.entity_id
    GROUP BY r.id
    ORDER BY COALESCE(r.updated_at, r.created_at) DESC
    '''
)

,id,user_id,created_at,updated_at,content,entities
0,22,1,2025-12-29T09:21:47.577Z,2025-12-29T09:21:47.577Z,앱에서 맥주 재고 확인하고 직접 마트 가니까 아무리 찾아도 못찾겠다. 집에 와서 보...,이마트
1,21,2,2025-12-29T09:20:45.197Z,2025-12-29T09:20:45.197Z,4개 한셋트 치약 1+1 세일한다기에 사고 보니 3개 한셋트 치약이었다. 영수증엔 ...,이마트
2,20,2,2025-12-29T09:20:17.511Z,2025-12-29T09:20:17.511Z,홈플러스 앱으로 와인 주문: 10만원 이상 사면 20%할인한다기에 가격 맞춰 3병 ...,홈플러스
3,19,1,2025-12-29T09:19:50.904Z,2025-12-29T09:19:50.904Z,정자동 정동마트에서 종종 바나나 세일을 하는데 대부분 거무죽죽하니 신선도 관리를 어...,정동마트
4,18,1,2025-12-29T09:18:58.976Z,2025-12-29T09:18:58.976Z,예전에 땡겨요에서 세일하길래 무슨 요리 배달 주문했더니 배달에 한시간 이상 걸린다고...,땡겨요
5,17,2,2025-12-29T09:18:02.078Z,2025-12-29T09:18:02.078Z,며칠이 니자도 발뒤꿈치가 아파 미금역 근처 정형외과를 찾아갔다. 아킬레스건염 같은 ...,미금더튼튼의원
6,16,2,2025-12-29T09:17:13.163Z,2025-12-29T09:17:13.163Z,발뒤꿈치가 아파 정형외과를 찾는데 저번에 비싼 주사 맞은데를 피해서 다른 병원을 갔...,"이주철마취과의원, 분당"
7,15,2,2025-12-29T09:16:18.396Z,2025-12-29T09:16:18.396Z,엄지 발가락이 아파서 동네 정형외과 갔다가 얼떨결에 비급여 10만원짜리 주사 맞고 ...,한사랑 정형외과의원
8,14,1,2025-12-29T09:15:40.337Z,2025-12-29T09:15:40.337Z,속초에서 시장 구경하고 돌아가는 길 닭강정 사는걸 깜빡했다. 많은 사람들이 만석닭강...,속초 동해닭강정
9,13,1,2025-12-29T09:15:16.784Z,2025-12-29T09:15:16.784Z,마트에서 풀무원 감자전/오징어부추전 구입. 에어프라이로 조리했는데 기름 범벅. 후라...,"풀무원 감자전, 풀무원 오징어부추전"
10,12,1,2025-12-29T09:14:35.950Z,2025-12-29T09:14:35.950Z,민생지원금으로 성남 할머니 족발에서 족발 포장. 잡내 없고 맛나다. 다음에 명성왕족...,"성남, 할머니족발"
11,11,1,2025-12-29T09:14:05.512Z,2025-12-29T09:14:05.512Z,귀한족발에서 족발 배달시켰는데 막국수 반찬까지 있는건 좋지만 정작 족발맛이 아쉽다,귀한족발
12,10,1,2025-12-29T09:13:40.947Z,2025-12-29T09:13:40.947Z,성남 현대시장 명성왕족발에서 족발 대자 포장. 싸고 맛 좋고 특히 온누리상품권을 쓸...,"명성왕족발, 성남현대시장"
13,9,1,2025-12-29T09:12:47.282Z,2025-12-29T09:12:47.282Z,굽네치킨에서 유일하게 좋아하는 고추바사삭. 근데 살이 너무 없는것 같다,"고추바사삭, 굽네치킨"
14,8,2,2025-12-29T08:36:49.478Z,2025-12-29T09:06:16.047Z,땡겨요에서 할인을 크게 해서 한동안 집앞 자담치킨 참 많이도 포장해 먹었다. 왓더핫...,"자담치킨, 땡겨요"
15,7,2,2025-12-29T08:35:56.715Z,None,교촌치킨에서 간장 레드 반반 주문. 간장만 먹으면 심심하고 레드만 먹으면 자극적이면...,교촌치킨 간장/레드 반반
16,6,2,2025-12-29T08:35:01.386Z,None,푸라닭에서 유명 쉐프와 협업했다는 깐풍치킨 주문. 소스가 볶은 느낌이 아니라 흥건하...,푸라닭 깐풍치킨
17,5,2,2025-12-29T07:59:37.482Z,None,노랑통닭은 순살도 가격이 더 비싸지 않아 좋다. 튀김 부스러기는 과자같이 바삭하니 ...,노랑통닭
18,4,2,2025-12-29T07:58:38.948Z,None,비비큐에서 맵소디 배달 주문. 양념 맛은 기억나지 않지만 소스 안쪽에서도 바삭한 식...,비비큐 맵소디
19,3,1,2025-12-29T07:54:49.553Z,None,배달앱에서 멕시카나 치킨 할인한다기에 주문하려했더니 미금점 영업을 하지 않는다. 이...,"멕시카나, 배민"
20,2,1,2025-12-29T07:53:41.320Z,None,처가집 양념통닭에서 마라치킨 주문. 그냥 달달한 양념 치킨에 마라향 살짝 추가한 정...,처가집 양념통닭 K마라치킨
21,1,1,2025-12-26T09:39:18.074Z,None,BHC서현시범단지점. 근처 지점중 배달 최수 주문가가 가장 저렴해 치킨 주문. 쏘마...,BHC 쏘마치

In [16]:
conn.close()

# entity

In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('entities.csv')
#df[['id','level','parent_id']] = df[['id','level','parent_id']].astype(int)
df = df.set_index('id')
df

              name      type  level  parent_id
id
1          BHC 쏘마치   product    NaN        NaN
2   처가집 양념통닭 K마라치킨   product    NaN        NaN
3             멕시카나    vendor    NaN        NaN
6             노랑통닭    vendor    NaN        NaN
9               배민    vendor    NaN        NaN
10         비비큐 맵소디   product    NaN        NaN
11        푸라닭 깐풍치킨   product    NaN        NaN
12   교촌치킨 간장/레드 반반   product    NaN        NaN
13            자담치킨    vendor    NaN        NaN
14             땡겨요    vendor    NaN        NaN
19           고추바사삭   product    NaN        NaN
20            굽네치킨    vendor    NaN        NaN
21           명성왕족발    vendor    NaN        NaN
22          성남현대시장    vendor    NaN        NaN
23            귀한족발    vendor    NaN        NaN
24              성남  location    NaN        NaN
25           할머니족발    vendor    NaN        NaN
26         풀무원 감자전   product    NaN        NaN
27      풀무원 오징어부추전   product    NaN        NaN
28        속초 동해닭강정    vendor    NaN        NaN
29      한사랑 정형외과의원    vendor    NaN        NaN
30        이주철마취과의원    vendor    NaN        NaN
31              분당  location    NaN        NaN
32         미금더튼튼의원    vendor    NaN        NaN
34            정동마트    vendor    NaN        NaN
35            홈플러스    vendor    NaN        NaN
36             이마트    vendor    NaN        NaN
37              치킨   product    NaN        NaN
38              병원   service    NaN        NaN
39              마트   service    NaN        NaN

In [10]:
ids = [1,2,10,11,19]
df.loc[ids, 'parent_id'] = 37
#df.loc[ids]

In [17]:
id = df.loc[df['name']=='치킨'].index[0]
df.loc[df['parent_id']==id]

              name     type  level  parent_id
id
1          BHC 쏘마치  product    NaN       37.0
2   처가집 양념통닭 K마라치킨  product    NaN       37.0
10         비비큐 맵소디  product    NaN       37.0
11        푸라닭 깐풍치킨  product    NaN       37.0
19           고추바사삭  product    NaN       37.0

치킨집: 굽네치킨, BHC, ...
굽네치킨: 치킨, 치즈볼, ... # menu of the restaurant '굽네치킨'
치킨: 쏘마치, K마라치킨, 맵소디, 깐풍치킨, 고추바사삭 # all chicken menu
성남시: 치킨집, 피자집, ...

성남시-굽네치킨's menu: 고추바사삭, ...