# Review data in app.sqlite

This notebook loads the local SQLite database and shows users, reviews, entities, and review-entity links.

In [10]:
import pandas as pd
import sqlite3
from pathlib import Path

db_path = Path('../entity-driven/data/app.sqlite')
if not db_path.exists():
    raise FileNotFoundError(f'Database not found at {db_path.resolve()}')

conn = sqlite3.connect(db_path)
conn.row_factory = sqlite3.Row

def show_old(query, params=None):
    params = params or ()
    cur = conn.execute(query, params)
    rows = cur.fetchall()
    return [dict(row) for row in rows]


def show(query, params=None):
    params = params or ()
    cur = conn.execute(query, params)
    rows = cur.fetchall()
    return pd.DataFrame(rows, columns=rows[0].keys() if rows else [])

In [11]:
# Users
show('SELECT * FROM user ORDER BY id')

   id user_id password
0   1     lbk     1234
1   2     kbl     1234

In [12]:
# Reviews (latest first)
show(
    'SELECT id, user_id, created_at, updated_at, content FROM review ORDER BY COALESCE(updated_at, created_at) DESC'
)

,id,user_id,created_at,updated_at,content
0,22,1,2025-12-29T09:21:47.577Z,2025-12-29T09:21:47.577Z,앱에서 맥주 재고 확인하고 직접 마트 가니까 아무리 찾아도 못찾겠다. 집에 와서 보...
1,21,2,2025-12-29T09:20:45.197Z,2025-12-29T09:20:45.197Z,4개 한셋트 치약 1+1 세일한다기에 사고 보니 3개 한셋트 치약이었다. 영수증엔 ...
2,20,2,2025-12-29T09:20:17.511Z,2025-12-29T09:20:17.511Z,홈플러스 앱으로 와인 주문: 10만원 이상 사면 20%할인한다기에 가격 맞춰 3병 ...
3,19,1,2025-12-29T09:19:50.904Z,2025-12-29T09:19:50.904Z,정자동 정동마트에서 종종 바나나 세일을 하는데 대부분 거무죽죽하니 신선도 관리를 어...
4,18,1,2025-12-29T09:18:58.976Z,2025-12-29T09:18:58.976Z,예전에 땡겨요에서 세일하길래 무슨 요리 배달 주문했더니 배달에 한시간 이상 걸린다고...
5,17,2,2025-12-29T09:18:02.078Z,2025-12-29T09:18:02.078Z,며칠이 니자도 발뒤꿈치가 아파 미금역 근처 정형외과를 찾아갔다. 아킬레스건염 같은 ...
6,16,2,2025-12-29T09:17:13.163Z,2025-12-29T09:17:13.163Z,발뒤꿈치가 아파 정형외과를 찾는데 저번에 비싼 주사 맞은데를 피해서 다른 병원을 갔...
7,15,2,2025-12-29T09:16:18.396Z,2025-12-29T09:16:18.396Z,엄지 발가락이 아파서 동네 정형외과 갔다가 얼떨결에 비급여 10만원짜리 주사 맞고 ...
8,14,1,2025-12-29T09:15:40.337Z,2025-12-29T09:15:40.337Z,속초에서 시장 구경하고 돌아가는 길 닭강정 사는걸 깜빡했다. 많은 사람들이 만석닭강...
9,13,1,2025-12-29T09:15:16.784Z,2025-12-29T09:15:16.784Z,마트에서 풀무원 감자전/오징어부추전 구입. 에어프라이로 조리했는데 기름 범벅. 후라...
10,12,1,2025-12-29T09:14:35.950Z,2025-12-29T09:14:35.950Z,민생지원금으로 성남 할머니 족발에서 족발 포장. 잡내 없고 맛나다. 다음에 명성왕족...
11,11,1,2025-12-29T09:14:05.512Z,2025-12-29T09:14:05.512Z,귀한족발에서 족발 배달시켰는데 막국수 반찬까지 있는건 좋지만 정작 족발맛이 아쉽다
12,10,1,2025-12-29T09:13:40.947Z,2025-12-29T09:13:40.947Z,성남 현대시장 명성왕족발에서 족발 대자 포장. 싸고 맛 좋고 특히 온누리상품권을 쓸...
13,9,1,2025-12-29T09:12:47.282Z,2025-12-29T09:12:47.282Z,굽네치킨에서 유일하게 좋아하는 고추바사삭. 근데 살이 너무 없는것 같다
14,8,2,2025-12-29T08:36:49.478Z,2025-12-29T09:06:16.047Z,땡겨요에서 할인을 크게 해서 한동안 집앞 자담치킨 참 많이도 포장해 먹었다. 왓더핫...
15,7,2,2025-12-29T08:35:56.715Z,None,교촌치킨에서 간장 레드 반반 주문. 간장만 먹으면 심심하고 레드만 먹으면 자극적이면...
16,6,2,2025-12-29T08:35:01.386Z,None,푸라닭에서 유명 쉐프와 협업했다는 깐풍치킨 주문. 소스가 볶은 느낌이 아니라 흥건하...
17,5,2,2025-12-29T07:59:37.482Z,None,노랑통닭은 순살도 가격이 더 비싸지 않아 좋다. 튀김 부스러기는 과자같이 바삭하니 ...
18,4,2,2025-12-29T07:58:38.948Z,None,비비큐에서 맵소디 배달 주문. 양념 맛은 기억나지 않지만 소스 안쪽에서도 바삭한 식...
19,3,1,2025-12-29T07:54:49.553Z,None,배달앱에서 멕시카나 치킨 할인한다기에 주문하려했더니 미금점 영업을 하지 않는다. 이...
20,2,1,2025-12-29T07:53:41.320Z,None,처가집 양념통닭에서 마라치킨 주문. 그냥 달달한 양념 치킨에 마라향 살짝 추가한 정...
21,1,1,2025-12-26T09:39:18.074Z,None,BHC서현시범단지점. 근처 지점중 배달 최수 주문가가 가장 저렴해 치킨 주문. 쏘마...

In [13]:
# Entities
show('SELECT * FROM entity ORDER BY id')

    id            name  type level parent_id
0    1         BHC 쏘마치  None  None      None
1    2  처가집 양념통닭 K마라치킨  None  None      None
2    3            멕시카나  None  None      None
3    4               배  None  None      None
4    5          비비큐 맵소  None  None      None
5    6            노랑통닭  None  None      None
6    9              배민  None  None      None
7   10         비비큐 맵소디  None  None      None
8   11        푸라닭 깐풍치킨  None  None      None
9   12   교촌치킨 간장/레드 반반  None  None      None
10  13            자담치킨  None  None      None
11  14             땡겨요  None  None      None
12  19           고추바사삭  None  None      None
13  20            굽네치킨  None  None      None
14  21           명성왕족발  None  None      None
15  22          성남현대시장  None  None      None
16  23            귀한족발  None  None      None
17  24              성남  None  None      None
18  25           할머니족발  None  None      None
19  26         풀무원 감자전  None  None      None
20  27      풀무원 오징어부추전  None  None      None
21  28        속초 동해닭강정  None  None      None
22  29      한사랑 정형외과의원  None  None      None
23  30        이주철마취과의원  None  None      None
24  31              분당  None  None      None
25  32         미금더튼튼의원  None  None      None
26  34            정동마트  None  None      None
27  35            홈플러스  None  None      None
28  36             이마트  None  None      None

In [14]:
# Review-entity links
show(
    'SELECT review_id, entity_id FROM review_entity ORDER BY review_id, entity_id'
)

    review_id  entity_id
0           1          1
1           2          2
2           3          3
3           3          9
4           4         10
5           5          6
6           6         11
7           7         12
8           8         13
9           8         14
10          9         19
11          9         20
12         10         21
13         10         22
14         11         23
15         12         24
16         12         25
17         13         26
18         13         27
19         14         28
20         15         29
21         16         30
22         16         31
23         17         32
24         18         14
25         19         34
26         20         35
27         21         36
28         22         36

In [7]:
# Joined view: reviews with entity names
show(
    '''
    SELECT r.id, r.user_id, r.created_at, r.updated_at, r.content,
           GROUP_CONCAT(e.name, ', ') AS entities
    FROM review r
    LEFT JOIN review_entity re ON r.id = re.review_id
    LEFT JOIN entity e ON e.id = re.entity_id
    GROUP BY r.id
    ORDER BY COALESCE(r.updated_at, r.created_at) DESC
    '''
)

[{'id': 22,
  'user_id': 1,
  'created_at': '2025-12-29T09:21:47.577Z',
  'updated_at': '2025-12-29T09:21:47.577Z',
  'content': '앱에서 맥주 재고 확인하고 직접 마트 가니까 아무리 찾아도 못찾겠다. 집에 와서 보니 여전히 앱에는 재고가 있다. 어디에 있었던걸까?',
  'entities': '이마트'},
 {'id': 21,
  'user_id': 2,
  'created_at': '2025-12-29T09:20:45.197Z',
  'updated_at': '2025-12-29T09:20:45.197Z',
  'content': '4개 한셋트 치약 1+1 세일한다기에 사고 보니 3개 한셋트 치약이었다. 영수증엔 여전히 4개 셋트로 표시되어있다. 귀찮아서 환불안하고 그냥 쓰려한다',
  'entities': '이마트'},
 {'id': 20,
  'user_id': 2,
  'created_at': '2025-12-29T09:20:17.511Z',
  'updated_at': '2025-12-29T09:20:17.511Z',
  'content': '홈플러스 앱으로 와인 주문: 10만원 이상 사면 20%할인한다기에 가격 맞춰 3병 결재하고 며칠뒤 배송을 기다리는데 배송 당일 2병 재고가 없다고 2병 취소 시키고 하나만 받으러 오라고 한다. 그러면 할인이 안되는데 살 이유가 없다. 다 취소하고 얼마뒤 보니 재고 없다던 와인 또 팔고 있더라. 또 주문했다가 당할까봐 그냥 포기',
  'entities': '홈플러스'},
 {'id': 19,
  'user_id': 1,
  'created_at': '2025-12-29T09:19:50.904Z',
  'updated_at': '2025-12-29T09:19:50.904Z',
  'content': '정자동 정동마트에서 종종 바나나 세일을 하는데 대부분 거무죽죽하니 신선도 관리를 어찌 하는지 황당하다',
  'entities': '정동마트'},
 {'id': 18,
  'user_id': 1,
  'created_at': '2025-12-29T09:18:58.976Z',
  'updated_at': '2025-12-29T09:18:58.976Z',
  'content': '예전에 땡겨요에서 세일하길래 무슨 요리 배달 주문했더니 배달에 한시간 이상 걸린다고 한다. 배민에서 같은 식당 찾아보면 그렇게 오래 걸리지 않는데 이상해 전화해서 물어보니 본사?에서 땡겨요 주문은 배달 시간을 길게 잡으라고 했더래나 뭐라나. 다행히 배달 취소하고 다른 곳에서 포장 주문. 앞으로 땡겨요는 포장만해야 겠다',
  'entities': '땡겨요'},
 {'id': 17,
  'user_id': 2,
  'created_at': '2025-12-29T09:18:02.078Z',
  'updated_at': '2025-12-29T09:18:02.078Z',
  'content': '며칠이 니자도 발뒤꿈치가 아파 미금역 근처 정형외과를 찾아갔다. 아킬레스건염 같은 병이라기에 주사도 몇번 맞으러 가고 물리치료는 여러번 받아 결국 다 낳았다. 시설도 좋고 의사 및 스태프도 다 친절해 좋았다',
  'entities': '미금더튼튼의원'},
 {'id': 16,
  'user_id': 2,
  'created_at': '2025-12-29T09:17:13.163Z',
  'updated_at': '2025-12-29T09:17:13.163Z',
  'content': '발뒤꿈치가 아파 정형외과를 찾는데 저번에 비싼 주사 맞은데를 피해서 다른 병원을 갔다. 갔더니 아픈 부위를 직접 보지도 않고 발모형에서 아픈 부위를 가리켜 보라고 한다. 뼈이상은 아닌것 같으니 엑스레이를 찍을 필요는 없다는 건 합리적이라 좋았지만. 물리치료 받으라는데 믿음이 안가 그냥 나왔따',
  'entities': '이주철마취과의원, 분당'},
 {'id': 15,
  'user_id': 2,
  'created_at': '2025-12-29T09:16:18.396Z',
  'updated_at': '2025-12-29T09:16:18.396Z',
  'content': '엄지 발가락이 아파서 동네 정형외과 갔다가 얼떨결에 비급여 10만원짜리 주사 맞고 왔다. 왠지 속은 기분',
  'entities': '한사랑 정형외과의원'},
 {'id': 14,
  'user_id': 1,
  'created_at': '2025-12-29T09:15:40.337Z',
  'updated_at': '2025-12-29T09:15:40.337Z',
  'content': '속초에서 시장 구경하고 돌아가는 길 닭강정 사는걸 깜빡했다. 많은 사람들이 만석닭강정 박스를 들고 다녔지만, 닭강정 맛이야 거기서 거기라 믿고 바로 보이는 동해닭강정에서 순살 닭강정(보통맛) 구입. 집에 가서 3일간 나눠 먹었는데 닭고기 부드럽고 잡내 하나 없어 만족',
  'entities': '속초 동해닭강정'},
 {'id': 13,
  'user_id': 1,
  'created_at': '2025-12-29T09:15:16.784Z',
  'updated_at': '2025-12-29T09:15:16.784Z',
  'content': '마트에서 풀무원 감자전/오징어부추전 구입. 에어프라이로 조리했는데 기름 범벅. 후라인팬에 구운건 좀 낫다. 귀찮더라도 전집에 가서 사먹던지 그냥 집에서 부침가루에 김치 넣고 부쳐먹는게 훨 낫다',
  'entities': '풀무원 감자전, 풀무원 오징어부추전'},
 {'id': 12,
  'user_id': 1,
  'created_at': '2025-12-29T09:14:35.950Z',
  'updated_at': '2025-12-29T09:14:35.950Z',
  'content': '민생지원금으로 성남 할머니 족발에서 족발 포장. 잡내 없고 맛나다. 다음에 명성왕족발이랑 맛을 비교해봐야겠다',
  'entities': '성남, 할머니족발'},
 {'id': 11,
  'user_id': 1,
  'created_at': '2025-12-29T09:14:05.512Z',
  'updated_at': '2025-12-29T09:14:05.512Z',
  'content': '귀한족발에서 족발 배달시켰는데 막국수 반찬까지 있는건 좋지만 정작 족발맛이 아쉽다',
  'entities': '귀한족발'},
 {'id': 10,
  'user_id': 1,
  'created_at': '2025-12-29T09:13:40.947Z',
  'updated_at': '2025-12-29T09:13:40.947Z',
  'content': '성남 현대시장 명성왕족발에서 족발 대자 포장. 싸고 맛 좋고 특히 온누리상품권을 쓸수 있어 좋다. 먹고 남은 족발 여러번 데워 먹었는데 감흥이 덜하다. 다음에는 소자 사서 먹어야 겠다',
  'entities': '명성왕족발, 성남현대시장'},
 {'id': 9,
  'user_id': 1,
  'created_at': '2025-12-29T09:12:47.282Z',
  'updated_at': '2025-12-29T09:12:47.282Z',
  'content': '굽네치킨에서 유일하게 좋아하는 고추바사삭. 근데 살이 너무 없는것 같다',
  'entities': '고추바사삭, 굽네치킨'},
 {'id': 8,
  'user_id': 2,
  'created_at': '2025-12-29T08:36:49.478Z',
  'updated_at': '2025-12-29T09:06:16.047Z',
  'content': '땡겨요에서 할인을 크게 해서 한동안 집앞 자담치킨 참 많이도 포장해 먹었다. 왓더핫, 불패, 맵쏘이 킥 돌아가며 먹었는데 모두 무난했던걸로 기억. 근데 간만에 주문하려니 뭐가 더 맛있었나 기억이 안난다.',
  'entities': '자담치킨, 땡겨요'},
 {'id': 7,
  'user_id': 2,
  'created_at': '2025-12-29T08:35:56.715Z',
  'updated_at': None,
  'content': '교촌치킨에서 간장 레드 반반 주문. 간장만 먹으면 심심하고 레드만 먹으면 자극적이면 이렇게 반반 먹으면 좋다',
  'entities': '교촌치킨 간장/레드 반반'},
 {'id': 6,
  'user_id': 2,
  'created_at': '2025-12-29T08:35:01.386Z',
  'updated_at': None,
  'content': '푸라닭에서 유명 쉐프와 협업했다는 깐풍치킨 주문. 소스가 볶은 느낌이 아니라 흥건하니 뿌린 느낌. 먹어본 치킨집 깐풍치킨중 최악',
  'entities': '푸라닭 깐풍치킨'},
 {'id': 5,
  'user_id': 2,
  'created_at': '2025-12-29T07:59:37.482Z',
  'updated_at': None,
  'content': '노랑통닭은 순살도 가격이 더 비싸지 않아 좋다. 튀김 부스러기는 과자같이 바삭하니 맛있다. 먹고 남은 치킨 에어프라이에 돌려 먹었는데 냄새가 좀 나는것 같다',
  'entities': '노랑통닭'},
 {'id': 4,
  'user_id': 2,
  'created_at': '2025-12-29T07:58:38.948Z',
  'updated_at': None,
  'content': '비비큐에서 맵소디 배달 주문. 양념 맛은 기억나지 않지만 소스 안쪽에서도 바삭한 식감이 느껴진건 기억한다',
  'entities': '비비큐 맵소디'},
 {'id': 3,
  'user_id': 1,
  'created_at': '2025-12-29T07:54:49.553Z',
  'updated_at': None,
  'content': '배달앱에서 멕시카나 치킨 할인한다기에 주문하려했더니 미금점 영업을 하지 않는다. 이러면 할인이 무슨 의미가 있나',
  'entities': '멕시카나, 배민'},
 {'id': 2,
  'user_id': 1,
  'created_at': '2025-12-29T07:53:41.320Z',
  'updated_at': None,
  'content': '처가집 양념통닭에서 마라치킨 주문. 그냥 달달한 양념 치킨에 마라향 살짝 추가한 정도. 닭고기 모든 부위 식감이 퍽퍽한것 같다.',
  'entities': '처가집 양념통닭 K마라치킨'},
 {'id': 1,
  'user_id': 1,
  'created_at': '2025-12-26T09:39:18.074Z',
  'updated_at': None,
  'content': 'BHC서현시범단지점. 근처 지점중 배달 최수 주문가가 가장 저렴해 치킨 주문. 쏘마치를 주문하려니 배달하기 천원이 모자라 마늘 토핑 추가 주문. 배달 받고 보니 서비스라고 콜라까지 보냈다. 따로 리뷰 요청도 없었는데. 마늘 토핑은 안쪽까지 바삭하니 과자 식감이 신기했다',
  'entities': 'BHC 쏘마치'}]

In [ ]:
conn.close()